run-name: Snyk Security Scan

on:
  pull_request:
    branches:
      - main  # O la rama en la que desees realizar el escaneo

jobs:
  snyk-scan:
    runs-on: [self-hosted, linux]  # Esto indica que usas un runner auto-hospedado en Linux

    steps:
      # Paso 1: Verificar que el código está bien clonado y listo
      - name: Checkout the repository
        uses: actions/checkout@v2

      # Paso 2: Verificar si Snyk CLI está instalado (opcional si ya lo tienes instalado globalmente)
      - name: Check if Snyk CLI is installed
      env:
      SNYCK_TOKEN: ${{secrets.SNYCK_TOKEN}}
        run: snyk --version

      # Paso 3: Crear el directorio de reporte (si no existe)
      - name: Create directory for reports
        run: |
          mkdir -p ~/Documents/IMF/desarrolloSeguro

      # Paso 4: Ejecutar el escaneo con Snyk y guardar el reporte en un archivo JSON
      - name: Run Snyk test and save the report locally
        run: snyk test --all-projects --json > ~/Documents/IMF/desarrolloSeguro/snyk-report.json
